language: node_js
if: tag IS blank
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 8.9 
  - 9
  - 10
script: make ci
jobs:
  include:
    - if: type != pull_request AND branch = master
      stage: Publish
      script: yarn semantic-release 
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
